/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 85
#define YY_END_OF_BUFFER 86
static yyconst short int yy_accept[229] =
    {   0,
        0,    0,   86,   85,    1,    4,   85,   85,   38,   27,
       85,   49,   50,   25,   23,   51,   24,   52,   26,   10,
       10,   53,   29,   39,   28,   37,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   45,   46,   47,   48,    1,   33,    0,
        9,    0,   44,    0,    0,   42,   40,   10,   10,   41,
       54,    0,    3,   43,    0,   10,   13,   10,   31,   32,
       30,   84,   84,   84,   59,   84,   84,   84,   84,   84,
       84,   84,   71,   84,   84,   84,   84,   84,   84,   84,
       62,   84,   84,   84,   84,   84,   35,   84,   84,   84,

       84,   84,   84,   74,   84,   84,   84,    9,    7,    0,
        7,    0,    0,    3,   10,   13,   84,   34,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   55,   84,   84,
       84,   84,   73,   84,   17,   84,   57,   84,   36,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,    8,    2,   84,   84,   84,   67,   16,   84,   84,
       84,   84,   84,   84,   64,   22,   84,   84,   84,   84,
       81,   75,   14,   84,   84,   84,   84,   84,   84,   63,
       76,    5,   56,   84,   83,   84,   69,   21,   80,   84,
       84,   84,   84,   84,   84,    6,   18,   84,   84,   84,

       84,   84,   84,   84,   72,   84,   84,   84,   82,   19,
       65,   84,   84,   78,   84,   60,   20,   77,   66,   15,
       84,   68,   79,   84,   61,   70,   58,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    1,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,    1,   20,
       21,   22,    1,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   30,   33,   34,   35,   36,   37,   38,
       30,   39,   40,   41,   42,   43,   44,   45,   30,   30,
       46,   47,   48,    1,   49,    1,   50,   25,   26,   27,

       51,   29,   30,   31,   32,   30,   33,   34,   35,   52,
       37,   38,   30,   53,   40,   54,   42,   43,   44,   45,
       30,   30,   55,    1,   56,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[57] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    3,    1,    1,
        1,    1,    1,    1,    1,    1,    4,    4,    1,    1,
        1,    1,    1,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    1,    1,    1,    4,    4,
        4,    4,    4,    4,    1,    1
    } ;

static yyconst short int yy_base[234] =
    {   0,
        0,    0,  348,  349,  345,  349,  325,   52,  349,  324,
      297,  349,  349,  322,  321,  349,   41,  349,   49,   49,
       54,  349,  320,  319,  318,  349,   39,   37,   58,   49,
       51,   64,    0,   32,  306,   65,   44,   80,   77,  293,
       78,  299,  304,  349,  349,  349,  349,  332,  349,   73,
      349,   76,  349,  325,  105,  349,  349,  109,  117,  349,
      349,  321,    0,  349,   94,  121,  123,  127,  349,  349,
      349,    0,  299,  303,    0,  292,   97,  288,   97,  113,
      110,  298,  284,  285,  122,  102,  290,  286,  112,  114,
        0,  119,  117,  123,  120,  288,    0,  131,  289,  295,

      145,  287,  144,    0,  276,  285,  284,  170,  349,  307,
      306,  302,  166,    0,  161,  163,  159,    0,  278,  161,
      159,  149,  271,  149,  168,  285,  163,    0,  274,  165,
      268,  170,    0,  281,    0,  273,    0,  165,    0,  271,
      170,  261,  269,  265,  259,  171,  161,  260,  173,  272,
      264,  349,  286,  256,  176,  262,    0,    0,  254,  174,
      261,  250,  171,  257,  256,    0,  186,  180,  186,  188,
        0,    0,    0,  194,  208,  249,  194,  195,  247,    0,
        0,    0,    0,  208,    0,  211,    0,    0,    0,  201,
      238,  211,  213,  241,  242,    0,    0,  231,  202,  203,

      234,  225,  213,  174,    0,  214,  154,  213,    0,    0,
        0,   89,   81,    0,  217,    0,    0,    0,    0,    0,
      223,    0,    0,  219,    0,    0,    0,  349,  274,  278,
       76,  282,  286
    } ;

static yyconst short int yy_def[234] =
    {   0,
      228,    1,  228,  228,  228,  228,  228,  229,  228,  228,
      230,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  228,  228,  228,  228,  228,  228,  229,
      228,  229,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  232,  233,  228,  228,  228,  228,  228,  228,  228,
      228,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,

      231,  231,  231,  231,  231,  231,  231,  229,  228,  228,
      228,  232,  232,  233,  228,  228,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  228,  232,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,

      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,    0,  228,  228,
      228,  228,  228
    } ;

static yyconst short int yy_nxt[406] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       33,   34,   33,   35,   33,   36,   37,   38,   39,   40,
       41,   33,   42,   43,   33,   44,    4,   45,    4,   27,
       31,   36,   39,   41,   46,   47,   51,   58,   59,   62,
       91,   60,   61,   65,   63,   66,   66,   92,   65,   64,
       68,   59,   73,   76,   74,   77,   82,   51,   75,   72,
      108,   78,   97,   92,   84,   83,   85,   87,   79,   77,
       74,   80,   94,   67,   81,   86,   97,   88,   52,   82,

       89,   95,   85,   98,  101,   90,   96,   78,  103,  110,
      115,  115,  111,   87,  104,   94,  105,  224,   99,   52,
      122,  100,   52,   65,  120,   66,   66,  101,  223,   98,
      105,   65,   99,   68,   59,   65,  123,   66,   66,  116,
      116,   65,  130,   68,   68,  124,  122,  120,  128,  134,
      133,  110,  136,   67,  110,  130,  110,  110,  110,  135,
      139,  124,  123,  129,  133,  134,  137,  138,  136,  141,
      144,  147,  135,  139,   51,  148,  113,  115,  115,  116,
      116,  153,  154,  141,  156,  145,  157,  158,  160,  161,
      165,  162,  167,  169,  147,  221,  180,  174,  145,  163,

      182,  158,  161,  186,  219,  172,  192,  196,  154,  157,
      156,  179,  180,  165,  189,  167,   52,  162,  172,  169,
      174,  195,  192,  182,  179,  186,  197,  189,  198,  199,
      196,  200,  202,  203,  206,  205,  207,  195,  209,  197,
      210,  198,  214,  215,  225,  199,  202,  203,  218,  220,
      226,  217,  207,  222,  227,  214,  215,  200,  205,  216,
      206,  209,  213,  210,  218,  220,  222,  225,  212,  211,
      227,  208,  204,  226,   50,   50,   50,   50,   54,   54,
      201,   54,  112,  112,  112,  112,  114,  194,  114,  114,
      193,  191,  190,  188,  187,  185,  113,  184,  183,  181,

      178,  177,  176,  175,  173,  171,  170,  168,  166,  164,
      159,  155,  113,  152,  152,  151,  150,  149,  146,  143,
      142,  140,  132,  131,  127,  126,  125,  121,  119,  118,
      117,  113,  109,   48,  107,  106,  102,   93,   71,   70,
       69,   57,   56,   55,   53,   49,   48,  228,    3,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,

      228,  228,  228,  228,  228
    } ;

static yyconst short int yy_chk[406] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    8,   17,   17,   19,
       34,   17,   17,   20,   19,   20,   20,   34,   21,   19,
       21,   21,   27,   28,   27,   28,   30,   50,   27,  231,
       52,   29,   37,   34,   31,   30,   31,   32,   29,   28,
       27,   29,   36,   20,   29,   31,   37,   32,    8,   30,

       32,   36,   31,   38,   39,   32,   36,   29,   41,   55,
       65,   65,   55,   32,   41,   36,   41,  213,   38,   50,
       79,   38,   52,   58,   77,   58,   58,   39,  212,   38,
       41,   59,   38,   59,   59,   66,   80,   66,   66,   67,
       67,   68,   86,   68,   68,   81,   79,   77,   85,   90,
       89,   55,   93,   58,   55,   86,   55,   55,   55,   92,
       95,   81,   80,   85,   89,   90,   94,   94,   93,   98,
      101,  103,   92,   95,  108,  103,  113,  115,  115,  116,
      116,  113,  117,   98,  120,  101,  121,  122,  124,  124,
      127,  125,  130,  132,  103,  207,  147,  141,  101,  125,

      149,  122,  124,  155,  204,  138,  163,  168,  117,  121,
      120,  146,  147,  127,  160,  130,  108,  125,  138,  132,
      141,  167,  163,  149,  146,  155,  169,  160,  170,  174,
      168,  175,  177,  178,  186,  184,  190,  167,  192,  169,
      193,  170,  199,  200,  215,  174,  177,  178,  203,  206,
      221,  202,  190,  208,  224,  199,  200,  175,  184,  201,
      186,  192,  198,  193,  203,  206,  208,  215,  195,  194,
      224,  191,  179,  221,  229,  229,  229,  229,  230,  230,
      176,  230,  232,  232,  232,  232,  233,  165,  233,  233,
      164,  162,  161,  159,  156,  154,  153,  151,  150,  148,

      145,  144,  143,  142,  140,  136,  134,  131,  129,  126,
      123,  119,  112,  111,  110,  107,  106,  105,  102,  100,
       99,   96,   88,   87,   84,   83,   82,   78,   76,   74,
       73,   62,   54,   48,   43,   42,   40,   35,   25,   24,
       23,   15,   14,   11,   10,    7,    5,    3,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,

      228,  228,  228,  228,  228
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner-flex.l"
#define INITIAL 0
#line 2 "scanner-flex.l"

int line_num = 1;	//counter for current line
int col_num = 0;	//counter for current column
#line 534 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 7 "scanner-flex.l"

									/*WhiteSpaces*/
#line 688 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 229 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 349 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 9 "scanner-flex.l"
{col_num += strlen(yytext); printf("");}
	YY_BREAK
/*Comments*/
case 2:
YY_RULE_SETUP
#line 12 "scanner-flex.l"
{printf("{COMMENT,\"%s\"}\n", yytext);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 13 "scanner-flex.l"
{printf("{COMMENT,\"%s\"}\n", yytext);}
	YY_BREAK
/*Statement Terminator*/
case 4:
YY_RULE_SETUP
#line 16 "scanner-flex.l"
{line_num++; col_num = 0; printf("NEWLINE \n");}
	YY_BREAK
/*Constant values*/
case 5:
YY_RULE_SETUP
#line 19 "scanner-flex.l"
{printf("{BOOLEAN,\"%s\"}\n", yytext);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 20 "scanner-flex.l"
{printf("{BOOLEAN,\"%s\"}\n", yytext);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 21 "scanner-flex.l"
{printf("{CHARACTER,\"%s\"}\n", yytext);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 22 "scanner-flex.l"
{printf("{CHARACTER,\"%s\"}\n", yytext);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 23 "scanner-flex.l"
{printf("{STRING,\"%s\"}\n", yytext);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 24 "scanner-flex.l"
{printf("{FLOATNUM,\"%s\"}\n", yytext);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 25 "scanner-flex.l"
{printf("{DECIMALINT,\"%s\"}\n", yytext);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 26 "scanner-flex.l"
{printf("{OCTALINT,\"%s\"}\n", yytext);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 27 "scanner-flex.l"
{printf("{HEXINT,\"%s\"}\n", yytext);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 28 "scanner-flex.l"
{printf("{NULL,\"%s\"}\n", yytext);}
	YY_BREAK
/*Data types*/
case 15:
YY_RULE_SETUP
#line 31 "scanner-flex.l"
{printf("{BOOLEAN, \"%s\"}\n", yytext);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 32 "scanner-flex.l"
{printf("{CHAR, \"%s\"}\n", yytext);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 33 "scanner-flex.l"
{printf("{INT, \"%s\"}\n", yytext);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 34 "scanner-flex.l"
{printf("{FLOAT, \"%s\"}\n", yytext);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 35 "scanner-flex.l"
{printf("{DOUBLE, \"%s\"}\n", yytext);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 36 "scanner-flex.l"
{printf("{RECORD, \"%s\"}\n", yytext);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 37 "scanner-flex.l"
{printf("{CLASS, \"%s\"}\n", yytext);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 38 "scanner-flex.l"
{printf("{ENUM, \"%s\"}\n", yytext);}
	YY_BREAK
/*Operators*/
case 23:
YY_RULE_SETUP
#line 41 "scanner-flex.l"
{printf("{ADD, \"%s\"}\n", yytext);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 42 "scanner-flex.l"
{printf("{SUB, \"%s\"}\n", yytext);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 43 "scanner-flex.l"
{printf("{MUL, \"%s\"}\n", yytext);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 44 "scanner-flex.l"
{printf("{DIV, \"%s\"}\n", yytext);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 45 "scanner-flex.l"
{printf("{MOD, \"%s\"}\n", yytext);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 47 "scanner-flex.l"
{printf("{GREATERTHAN, \"%s\"}\n", yytext);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 48 "scanner-flex.l"
{printf("{LESSTHAN, \"%s\"}\n", yytext);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 49 "scanner-flex.l"
{printf("{GREATEREQUAL, \"%s\"}\n", yytext);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 50 "scanner-flex.l"
{printf("{LESSEQUAL, \"%s\"}\n", yytext);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 52 "scanner-flex.l"
{printf("{EQUALTO, \"%s\"}\n", yytext);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 53 "scanner-flex.l"
{printf("{NOTEQUAL, \"%s\"}\n", yytext);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 55 "scanner-flex.l"
{printf("{AND, \"%s\"}\n", yytext);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 56 "scanner-flex.l"
{printf("{OR, \"%s\"}\n", yytext);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 57 "scanner-flex.l"
{printf("{NOT, \"%s\"}\n", yytext);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 59 "scanner-flex.l"
{printf("{ATSIGN, \"%s\"}\n", yytext);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 60 "scanner-flex.l"
{printf("{NUMBERSIGN, \"%s\"}\n", yytext);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 62 "scanner-flex.l"
{printf("{ASSIGNMENT, \"%s\"}\n", yytext);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 63 "scanner-flex.l"
{printf("{ADDASS, \"%s\"}\n", yytext);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 64 "scanner-flex.l"
{printf("{SUBASS, \"%s\"}\n", yytext);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 65 "scanner-flex.l"
{printf("{MULASS, \"%s\"}\n", yytext);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 66 "scanner-flex.l"
{printf("{DIVASS, \"%s\"}\n", yytext);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 67 "scanner-flex.l"
{printf("{MODASS, \"%s\"}\n", yytext);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 69 "scanner-flex.l"
{printf("{LEFTBRACKET, \"%s\"}\n", yytext);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 70 "scanner-flex.l"
{printf("{RIGHTBRACKET, \"%s\"}\n", yytext);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 71 "scanner-flex.l"
{printf("{LEFTBRACE, \"%s\"}\n", yytext);}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 72 "scanner-flex.l"
{printf("{RIGHTBRACE, \"%s\"}\n", yytext);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 73 "scanner-flex.l"
{printf("{LEFTPAREN, \"%s\"}\n", yytext);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 74 "scanner-flex.l"
{printf("{RIGHTPAREN, \"%s\"}\n", yytext);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 76 "scanner-flex.l"
{printf("{COMMA, \"%s\"}\n", yytext);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 77 "scanner-flex.l"
{printf("{DOT, \"%s\"}\n", yytext);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 78 "scanner-flex.l"
{printf("{COLON, \"%s\"}\n", yytext);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 79 "scanner-flex.l"
{printf("{ARROW, \"%s\"}\n", yytext);}
	YY_BREAK
/*Keywords*/
case 55:
YY_RULE_SETUP
#line 82 "scanner-flex.l"
{printf("{END, \"%s\"}\n", yytext);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 83 "scanner-flex.l"
{printf("{VOID, \"%s\"}\n", yytext);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 84 "scanner-flex.l"
{printf("{NEW, \"%s\"}\n", yytext);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 85 "scanner-flex.l"
{printf("{FUNCTION, \"%s\"}\n", yytext);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 86 "scanner-flex.l"
{printf("{AS, \"%s\"}\n", yytext);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 87 "scanner-flex.l"
{printf("{PUBLIC, \"%s\"}\n", yytext);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 88 "scanner-flex.l"
{printf("{PRIVATE, \"%s\"}\n", yytext);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 89 "scanner-flex.l"
{printf("{IF, \"%s\"}\n", yytext);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 90 "scanner-flex.l"
{printf("{THEN, \"%s\"}\n", yytext);}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 91 "scanner-flex.l"
{printf("{ELSE, \"%s\"}\n", yytext);}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 92 "scanner-flex.l"
{printf("{ELSEIF, \"%s\"}\n", yytext);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 93 "scanner-flex.l"
{printf("{SWITCH, \"%s\"}\n", yytext);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 94 "scanner-flex.l"
{printf("{CASE, \"%s\"}\n", yytext);}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 95 "scanner-flex.l"
{printf("{DEFAULT, \"%s\"}\n", yytext);}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 96 "scanner-flex.l"
{printf("{BREAK, \"%s\"}\n", yytext);}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 97 "scanner-flex.l"
{printf("{CONTINUE, \"%s\"}\n", yytext);}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 98 "scanner-flex.l"
{printf("{DO, \"%s\"}\n", yytext);}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 99 "scanner-flex.l"
{printf("{WHILE, \"%s\"}\n", yytext);}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 100 "scanner-flex.l"
{printf("{FOR, \"%s\"}\n", yytext);}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 101 "scanner-flex.l"
{printf("{TO, \"%s\"}\n", yytext);}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 102 "scanner-flex.l"
{printf("{NEXT, \"%s\"}\n", yytext);}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 103 "scanner-flex.l"
{printf("{THIS, \"%s\"}\n", yytext);}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 104 "scanner-flex.l"
{printf("{RETURN, \"%s\"}\n", yytext);}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 105 "scanner-flex.l"
{printf("{PARENT, \"%s\"}\n", yytext);}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 106 "scanner-flex.l"
{printf("{EXTENDS, \"%s\"}\n", yytext);}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 107 "scanner-flex.l"
{printf("{CONST, \"%s\"}\n", yytext);}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 108 "scanner-flex.l"
{printf("{LINK, \"%s\"}\n", yytext);}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 109 "scanner-flex.l"
{printf("{DEFINE, \"%s\"}\n", yytext);}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 110 "scanner-flex.l"
{printf("{ALIAS, \"%s\"}\n", yytext);}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 112 "scanner-flex.l"
{printf("{IDENTIFIER, \"%s\"}\n", yytext);}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 115 "scanner-flex.l"
ECHO;
	YY_BREAK
#line 1202 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 229 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 229 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 228);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 115 "scanner-flex.l"


int main(argc, argv)
int argc;
char **argv;
{
	if(argc > 1) {
		if(!(yyin = fopen(argv[1], "r"))) {
			perror(argv[1]);
			return (1);
		}
	}
	yylex();
	printf("Lines: %d\n", line_num);
}